3250 Foundations of Data Science Jan-April 2020 <br>
Group 7 <br>
Member: Albert Mendoza <br>
Prof: Irina Sedenko

# Getting Per- Capita of Canadian Citizens Immigrated

    - Divide the original dataset by total population of the country and get percentage

In [6]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [7]:
dfcancitizen = pd.read_csv("cleanedcanadaimmigration.csv",
                           index_col = "Country"
                          )
dfcancitizen

,Region,Status,1980,1981,1982,1983,1984,1985,1986,1987,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Developing regions,16,39,39,47,71,340,496,741,...,1758,2203,2635,2004,1943.0,1882,1596,1187,1342,1977
Albania,Europe,Developed regions,1,0,0,0,0,0,1,2,...,561,539,620,603,603.5,604,359,229,454,631
Algeria,Africa,Developing regions,80,67,71,69,63,44,69,132,...,4752,4325,3774,4331,5013.0,5695,2468,2004,3340,4243
American Samoa,Oceania,Developing regions,0,1,0,0,0,0,0,1,...,0,0,0,0,0.0,0,1,0,0,1
Andorra,Europe,Developed regions,0,0,0,0,0,0,2,0,...,0,0,1,1,0.5,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,Latin America and the Caribbean,Developing regions,103,117,174,124,142,165,179,229,...,998,1452,1373,1022,1303.0,1584,712,588,1277,1690
Vietnam,Asia,Developing regions,1191,1829,2162,3404,7583,5907,2741,1406,...,1942,1723,1731,2112,2035.5,1959,1163,810,1769,2593
Yemen,Asia,Developing regions,1,2,1,6,0,18,7,12,...,211,160,174,217,199.0,181,115,80,216,230
Zambia,Africa,Developing regions,11,17,11,7,16,9,15,23,...,102,69,46,59,94.0,129,78,54,75,104
Zimbabwe,Africa,Developing regions,72,114,102,44,32,29,43,68,...,494,434,437,407,515.5,624,362,235,361,413

In [8]:
dfpopulation = pd.read_csv("cleanedworldnew.csv",
                           index_col = "Country"
                          )
dfpopulation

ValueError: Index Country invalid

In [5]:

tempregion = dfcancitizen["Region"]
tempstatus = dfcancitizen["Status"]

In [40]:
#combining both datasets
dfcombined = (dfcancitizen / dfpopulation) * 100
dfcombined

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2012,2013,2014,2015,2016,2017,2018,2019,Region,Status
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.026624,0.064392,0.063575,0.075561,0.112993,0.539460,0.791776,1.198389,1.355621,1.763010,...,2.569228,1.942632,1.872338,1.803701,1.521855,1.126549,1.267892,NaN,NaN,NaN
Albania,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000009,0.000017,0.000017,0.000025,...,0.001990,0.001869,0.001808,0.001755,0.001015,0.000631,0.001221,NaN,NaN,NaN
Algeria,0.000959,0.000775,0.000793,0.000744,0.000655,0.000442,0.000669,0.001235,0.002186,0.003789,...,0.015031,0.016648,0.018607,0.020424,0.008557,0.006721,0.010841,NaN,NaN,NaN
American Samoa,0.000000,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000032,0.000000,0.000031,...,0.000000,0.000000,0.000000,0.000000,0.000035,0.000000,0.000000,NaN,NaN,NaN
Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004300,0.000000,0.000000,0.000000,...,0.001213,0.001238,0.000631,0.000000,0.000000,0.001299,0.001299,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,0.000004,0.000007,0.000003,0.000019,0.000000,0.000055,0.000021,0.000035,0.000020,0.000050,...,0.000329,0.000404,0.000365,0.000327,0.000205,0.000140,0.000374,NaN,NaN,NaN
Zambia,0.000188,0.000281,0.000176,0.000108,0.000239,0.000130,0.000210,0.000312,0.000579,0.000870,...,0.000318,0.000395,0.000610,0.000812,0.000477,0.000320,0.000432,NaN,NaN,NaN
Zimbabwe,0.000972,0.001485,0.001282,0.000533,0.000374,0.000327,0.000467,0.000714,0.001005,0.001842,...,0.003332,0.003049,0.003794,0.004517,0.002580,0.001651,0.002500,NaN,NaN,NaN

In [41]:
# adding back the Region and status
dfcombined["Region"]=tempregion
dfcombined["Status"]=tempstatus
dfcombined

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2012,2013,2014,2015,2016,2017,2018,2019,Region,Status
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.026624,0.064392,0.063575,0.075561,0.112993,0.539460,0.791776,1.198389,1.355621,1.763010,...,2.569228,1.942632,1.872338,1.803701,1.521855,1.126549,1.267892,NaN,Asia,Developing regions
Albania,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000009,0.000017,0.000017,0.000025,...,0.001990,0.001869,0.001808,0.001755,0.001015,0.000631,0.001221,NaN,Europe,Developed regions
Algeria,0.000959,0.000775,0.000793,0.000744,0.000655,0.000442,0.000669,0.001235,0.002186,0.003789,...,0.015031,0.016648,0.018607,0.020424,0.008557,0.006721,0.010841,NaN,Africa,Developing regions
American Samoa,0.000000,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000032,0.000000,0.000031,...,0.000000,0.000000,0.000000,0.000000,0.000035,0.000000,0.000000,NaN,Oceania,Developing regions
Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004300,0.000000,0.000000,0.000000,...,0.001213,0.001238,0.000631,0.000000,0.000000,0.001299,0.001299,NaN,Europe,Developed regions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,0.000004,0.000007,0.000003,0.000019,0.000000,0.000055,0.000021,0.000035,0.000020,0.000050,...,0.000329,0.000404,0.000365,0.000327,0.000205,0.000140,0.000374,NaN,Asia,Developing regions
Zambia,0.000188,0.000281,0.000176,0.000108,0.000239,0.000130,0.000210,0.000312,0.000579,0.000870,...,0.000318,0.000395,0.000610,0.000812,0.000477,0.000320,0.000432,NaN,Africa,Developing regions
Zimbabwe,0.000972,0.001485,0.001282,0.000533,0.000374,0.000327,0.000467,0.000714,0.001005,0.001842,...,0.003332,0.003049,0.003794,0.004517,0.002580,0.001651,0.002500,NaN,Africa,Developing regions

In [42]:
#drop NA
dfdropped = dfcombined.dropna(how='all')
dfdropped

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2012,2013,2014,2015,2016,2017,2018,2019,Region,Status
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.026624,0.064392,0.063575,0.075561,0.112993,0.539460,0.791776,1.198389,1.355621,1.763010,...,2.569228,1.942632,1.872338,1.803701,1.521855,1.126549,1.267892,NaN,Asia,Developing regions
Albania,0.000007,0.000000,0.000000,0.000000,0.000000,0.000000,0.000009,0.000017,0.000017,0.000025,...,0.001990,0.001869,0.001808,0.001755,0.001015,0.000631,0.001221,NaN,Europe,Developed regions
Algeria,0.000959,0.000775,0.000793,0.000744,0.000655,0.000442,0.000669,0.001235,0.002186,0.003789,...,0.015031,0.016648,0.018607,0.020424,0.008557,0.006721,0.010841,NaN,Africa,Developing regions
American Samoa,0.000000,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000032,0.000000,0.000031,...,0.000000,0.000000,0.000000,0.000000,0.000035,0.000000,0.000000,NaN,Oceania,Developing regions
Andorra,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004300,0.000000,0.000000,0.000000,...,0.001213,0.001238,0.000631,0.000000,0.000000,0.001299,0.001299,NaN,Europe,Developed regions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0.089103,0.098700,0.143334,0.099832,0.111768,0.126939,0.134592,0.168285,0.200266,0.212894,...,0.550303,0.398231,0.493770,0.584222,0.255811,0.205947,0.436313,NaN,Latin America and the Caribbean,Developing regions
Vietnam,0.000027,0.000041,0.000047,0.000073,0.000159,0.000122,0.000056,0.000028,0.000028,0.000058,...,0.000024,0.000029,0.000028,0.000027,0.000016,0.000011,0.000023,NaN,Asia,Developing regions
Yemen,0.000004,0.000007,0.000003,0.000019,0.000000,0.000055,0.000021,0.000035,0.000020,0.000050,...,0.000329,0.000404,0.000365,0.000327,0.000205,0.000140,0.000374,NaN,Asia,Developing regions
Zambia,0.000188,0.000281,0.000176,0.000108,0.000239,0.000130,0.000210,0.000312,0.000579,0.000870,...,0.000318,0.000395,0.000610,0.000812,0.000477,0.000320,0.000432,NaN,Africa,Developing regions
Zimbabwe,0.000972,0.001485,0.001282,0.000533,0.000374,0.000327,0.000467,0.000714,0.001005,0.001842,...,0.003332,0.003049,0.003794,0.004517,0.002580,0.001651,0.002500,NaN,Africa,Developing regions

In [43]:
dfdropped.to_csv("cleanedcombined.csv")